# Generated by Django 3.0.4 on 2020-04-08 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_shelf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='who_ownes',
            field=models.CharField(default='YOU', max_length=50),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
