# Generated by Django 3.0.4 on 2020-04-08 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_shelf', '0002_auto_20200408_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='shelf',
            field=models.CharField(default=1, max_length=1),
        ),
    ]
