# Generated by Django 3.0.4 on 2020-04-08 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_shelf', '0003_book_shelf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='shelf',
        ),
    ]
